// <auto-generated />
using System;
using IssaWPF6.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IssaWPF6.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230919035509_AddPhotoTables")]
    partial class AddPhotoTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IssaWPF6.Models.Colon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .HasColumnType("text");

                    b.Property<string>("AnalInspection")
                        .HasColumnType("text");

                    b.Property<string>("Assistant")
                        .HasColumnType("text");

                    b.Property<string>("ClinicalData")
                        .HasColumnType("text");

                    b.Property<string>("ColonDetails")
                        .HasColumnType("text");

                    b.Property<string>("Conclusion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endoscopist")
                        .HasColumnType("text");

                    b.Property<string>("FileNo")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("Ileum")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PRExam")
                        .HasColumnType("text");

                    b.Property<string>("Premedication")
                        .HasColumnType("text");

                    b.Property<string>("Preparation")
                        .HasColumnType("text");

                    b.Property<string>("Rectum")
                        .HasColumnType("text");

                    b.Property<string>("ReferredDoctor")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Colons");
                });

            modelBuilder.Entity("IssaWPF6.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("IssaWPF6.Models.Stomach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .HasColumnType("text");

                    b.Property<string>("Assistant")
                        .HasColumnType("text");

                    b.Property<string>("ClinicalData")
                        .HasColumnType("text");

                    b.Property<string>("Conclusion")
                        .HasColumnType("text");

                    b.Property<string>("D1")
                        .HasColumnType("text");

                    b.Property<string>("D2")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endoscopist")
                        .HasColumnType("text");

                    b.Property<string>("Esophagus")
                        .HasColumnType("text");

                    b.Property<string>("FileNo")
                        .HasColumnType("text");

                    b.Property<string>("GEJ")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Premedication")
                        .HasColumnType("text");

                    b.Property<string>("ReferredDoctor")
                        .HasColumnType("text");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.Property<string>("StomachDetails")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stomaches");
                });
#pragma warning restore 612, 618
        }
    }
}
